# Generated by Django 2.2.10 on 2021-06-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_noticekind_days'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='noticekind',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='noticekind',
            name='app',
        ),
    ]
