# Generated by Django 2.2.10 on 2021-06-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_auto_20210602_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticekind',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
