# Generated by Django 2.2.24 on 2021-06-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0006_auto_20210613_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticekind',
            name='template',
            field=models.TextField(max_length=2048),
        ),
    ]
