# Generated by Django 2.1.2 on 2018-10-31 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_badge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='article',
            new_name='event',
        ),
        # migrations.AlterField(
            # model_name='badge',
            # name='category_color',
            # field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        # ),
        # migrations.AlterField(
            # model_name='badge',
            # name='name_color',
            # field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        # ),
        # migrations.AlterField(
            # model_name='badge',
            # name='number_color',
            # field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        # ),
    ]
