# Generated by Django 2.0.7 on 2018-07-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180714_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='release_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
