# Generated by Django 2.1.2 on 2018-11-11 20:10

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    WaitingList = apps.get_model('events', 'WaitingList')
    for wl in WaitingList.objects.all():
        wl.buy_code = uuid.uuid4()
        wl.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='buy_code',
            field=models.UUIDField(default=None, blank=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='waitinglist',
            name='buy_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
