# Generated by Django 2.1.4 on 2019-04-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20190421_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='slug',
            new_name='hashtag',
        ),
    ]
