# Generated by Django 2.2.4 on 2019-08-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_external_tickets_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='closed_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
