# Generated by Django 2.2.24 on 2022-05-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_closed_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cfp_start_at',
            field=models.DateTimeField(blank=True, default=None, help_text='First day of Call for Papers period', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='cfp_stop_at',
            field=models.DateTimeField(blank=True, default=None, help_text='End of Call for Papers period (This day is not included)', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=models.ImageField(blank=True, help_text='Should be squared (250x250 max). Shown in events list.', upload_to='events/event/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.TextField(blank=True, help_text='Shown in events list'),
        ),
    ]
