# Generated by Django 3.2.13 on 2022-05-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20220510_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='proposal',
            name='description',
            field=models.TextField(help_text='Cuéntamos en dos o tres párrafos tu propuesta de charla.', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='surname',
            field=models.CharField(max_length=256, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='title',
            field=models.CharField(max_length=340, verbose_name='Título'),
        ),
    ]
