# Generated by Django 6.1.1 on 2026-09-25 13:03

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_auto_20220516_1802"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Trade",
        ),
        migrations.AlterField(
            model_name="badge",
            name="category_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="name_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="number_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="default_slot_duration",
            field=models.DurationField(
                default=3000,
                help_text="En segundos, por ejemplo 50 minutos = 3000 (50*60)",
            ),
        ),
    ]
