# Generated by Django 3.2.23 on 2025-02-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20250224_1216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
