# Generated by Django 3.2.25 on 2025-03-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_delete_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='category_color',
            field=models.CharField(default='#FFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name_color',
            field=models.CharField(default='#FFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='badge',
            name='number_color',
            field=models.CharField(default='#FFFFFF', max_length=18),
        ),
    ]
