# Generated by Django 2.2.3 on 2019-10-13 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(choices=[(0, 'Presidente'), (0, 'Vicepresidente'), (1, 'Secretario'), (2, 'Tesorero'), (3, 'Vocal 1'), (4, 'Vocal 2'), (5, 'Vocal 3'), (5, 'Vocal 4')])),
                ('since', models.DateField(auto_now_add=True)),
                ('until', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.Member')),
            ],
        ),
    ]
