# Generated by Django 2.2.7 on 2019-12-01 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField()),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateField()),
                ('amount', models.FloatField(choices=[(20, 'General'), (10, 'Estudiante y/o Desempleado')], default=20)),
                ('payment_type', models.CharField(choices=[('BT', 'Transferencia bancaria'), ('ST', 'Stripe'), ('PP', 'PayPal')], default='BT', max_length=2)),
                ('payment_reference', models.CharField(blank=True, max_length=128)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.Member')),
            ],
        ),
    ]
