# Generated by Django 2.2.7 on 2019-12-01 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20191201_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_category', models.CharField(choices=[('F', 'Socio/a fundador/a'), ('N', 'Socio/a de número'), ('H', 'Socio/a honorífico/a')], default='N', max_length=1)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('fee_received_at', models.DateTimeField(blank=True)),
                ('fee_amount', models.FloatField(blank=True, choices=[(20, 'General'), (10, 'Estudiante y/o Desempleado'), (0, 'Exento')], default=20, null=True)),
                ('fee_payment_type', models.CharField(choices=[('BT', 'Transferencia bancaria'), ('ST', 'Stripe'), ('PP', 'PayPal')], default='BT', max_length=2)),
                ('fee_payment_reference', models.CharField(blank=True, max_length=128)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.Member')),
            ],
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
    ]
