# Generated by Django 2.2.7 on 2019-12-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20191201_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_until',
        ),
    ]
