# Generated by Django 2.2.7 on 2019-12-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20191201_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='since',
            field=models.DateField(),
        ),
    ]
