# Generated by Django 2.2.7 on 2019-12-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20191201_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='remarks',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='membership',
            name='remarks',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='position',
            name='remarks',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
