# Generated by Django 2.2.10 on 2020-11-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_auto_20191202_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='po_box',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código postal'),
        ),
    ]
