# Generated by Django 2.2.10 on 2020-11-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_auto_20201125_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=120)),
                ('role_desc', models.TextField(blank=True)),
                ('weight', models.IntegerField(default=100)),
            ],
        ),
    ]
