# Generated by Django 2.2.20 on 2021-06-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_auto_20210524_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('id', 'user__first_name', 'user__last_name'), 'verbose_name': 'Socio', 'verbose_name_plural': 'Socios'},
        ),
    ]
