# Generated by Django 2.2.10 on 2020-11-25 19:03

from django.db import migrations


def create_roles(apps, schema_editor):
    Role = apps.get_model('members', 'Role')
    for (pkey, name, weight) in [
            ('PRE', 'Presidencia', 100),
            ('VPR', 'Vicepresidencia', 200),
            ('SEC', 'Secretaría', 300),
            ('TRE', 'Tesorería', 400),
            ('VOC', 'Vocalía', 500),
            ]:
        role = Role(id=pkey, role_name=name, weight=weight)
        role.save()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_create_model_role'),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
