# Generated by Django 2.2.24 on 2021-09-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_auto_20210604_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=320),
        ),
    ]
