# Generated by Django 2.2.24 on 2021-09-22 18:45

from django.db import migrations


def get_email_from_user(apps, schema_editor):
    Member = apps.get_model('members', 'Member')
    for member in Member.objects.all():
        member.email = member.user.email
        member.save()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_member_email'),
    ]

    operations = [
        migrations.RunPython(get_email_from_user)
    ]
