# Generated by Django 2.2.24 on 2021-09-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_copy_member_email_from_user_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=320, unique=True),
        ),
    ]
