# Generated by Django 2.2.10 on 2020-12-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_remove_field_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='weight',
            field=models.IntegerField(default=100, help_text='Orden relativo a los demas roles. Los más ligeros primero'),
        ),
    ]
