# Generated by Django 2.2.10 on 2020-11-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_auto_20220510_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código postal'),
        ),
    ]
