# Generated by Django 6.1.1 on 2026-09-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0026_auto_20220510_2236"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={
                "ordering": ("since", "position", "member"),
                "verbose_name": "Junta de gobierno",
            },
        ),
    ]
