# Generated by Django 2.2.10 on 2020-11-25 19:28

from django.db import migrations



def set_roles(apps, schema_editor):
    Position = apps.get_model('members', 'Position')
    Role = apps.get_model('members', 'Role')
    for position in Position.objects.all():
        if position.position in ['PRE', 'VPR', 'SEC', 'TRE']:
            position.role = Role.objects.get(pk=position.position)
        else:
            position.role = Role.objects.get(pk='VOC')
        position.save()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_position_role'),
    ]

    operations = [
        migrations.RunPython(set_roles),
    ]
