# Generated by Django 2.2.10 on 2020-11-25 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_set_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('role__weight',)},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('weight',)},
        ),
        migrations.RemoveField(
            model_name='position',
            name='position',
        ),
        migrations.AlterField(
            model_name='position',
            name='role',
            field=models.ForeignKey(default='VOC', on_delete=django.db.models.deletion.PROTECT, to='members.Role'),
        ),
    ]
