# Generated by Django 3.2.23 on 2025-02-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0033_auto_20201204_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
