# Generated by Django 2.1 on 2018-08-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hero',
            field=models.ImageField(blank=True, upload_to='events/event/'),
        ),
    ]
