# Generated by Django 2.1.2 on 2018-11-11 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '__first__'),
        ('events', '0005_waitinglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('fixed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Event')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.Ticket')),
            ],
        ),
    ]
