# Generated by Django 2.1.4 on 2019-03-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=models.ImageField(blank=True, help_text="Should be squared (250x250 max). Shown in events' list", upload_to='events/event/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Shown in main page of event (markdown allowed)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hero',
            field=models.ImageField(blank=True, help_text='Enough 1200px wide. Shown shaded in main page of event', upload_to='events/event/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.TextField(blank=True, help_text="Shown in events' list"),
        ),
    ]
