# Generated by Django 2.1.4 on 2019-04-20 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_venue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date']},
        ),
    ]
