# Generated by Django 2.2 on 2019-07-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20190421_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_tickets_url',
            field=models.URLField(blank=True, help_text='Should be filled if tickets are sold outside our site'),
        ),
    ]
