# Generated by Django 2.1.3 on 2018-12-31 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=120)),
                ('rest_address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('taxes', models.IntegerField(choices=[(0, 'IGIC(7%)'), (1, 'exto IGIC'), (2, 'iva (21%)')])),
                ('retention', models.IntegerField(choices=[(0, 'NO RETENTION'), (1, 'IRPF 6%'), (2, 'IRPF 12%'), (3, 'IRPF 21%')])),
                ('invoice_number', models.IntegerField(blank=True)),
                ('proforma', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Client')),
            ],
        ),
        migrations.AddField(
            model_name='concept',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
        ),
    ]
