# Generated by Django 3.2.16 on 2023-11-14 00:05

import apps.certificates.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0019_auto_20220516_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description and purpouse of certificate', max_length=256)),
                ('template', models.FileField(help_text='Template to be used to generate PDF', max_length=512, upload_to=apps.certificates.models._certificates_upload_to)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='This certificate related event', on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='events.event')),
            ],
            options={
                'verbose_name': 'certificado',
                'verbose_name_plural': 'certificados',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre propio', max_length=256, verbose_name='Nombre')),
                ('surname', models.CharField(help_text='Apellidos', max_length=384, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, default=None, help_text='Correo electrónico al que remitir el certificado', max_length=256, null=True, verbose_name='E-Mail')),
                ('extra', models.CharField(help_text='Información extra para el cerificado', max_length=512, verbose_name='Información extra')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Id. público del certificado')),
                ('pdf', models.FileField(blank=True, default=None, editable=False, help_text='Generated PDF', max_length=512, null=True, upload_to=apps.certificates.models._issued_certificates_upload_to)),
                ('issued_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='Fecha de expedición')),
                ('certificate', models.ForeignKey(help_text='Modelo del certificado', on_delete=django.db.models.deletion.PROTECT, related_name='attendees', to='certificates.certificate', verbose_name='Certificado que solicita')),
            ],
            options={
                'verbose_name': 'asistente',
                'verbose_name_plural': 'asistentes',
                'ordering': ['name', 'surname'],
            },
        ),
    ]
