# Generated by Django 3.2.16 on 2023-11-05 15:48

import apps.certificates.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0019_auto_20220516_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description and purpouse of certificate', max_length=256)),
                ('template', models.FileField(help_text='Template to be used to generate PDF', max_length=512, upload_to=apps.certificates.models._certificates_upload_dir)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='This certificate related event', on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='events.event')),
            ],
            options={
                'verbose_name': 'certificado',
                'verbose_name_plural': 'certificados',
                'ordering': ['description'],
            },
        ),
    ]
