# Generated by Django 3.2.23 on 2023-11-05 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('surname', models.CharField(max_length=384)),
                ('event', models.ForeignKey(help_text='Attendee event', on_delete=django.db.models.deletion.PROTECT, related_name='Attendees', to='events.event')),
            ],
            options={
                'verbose_name': 'asistente',
                'verbose_name_plural': 'asistentes',
                'ordering': ['name', 'surname'],
            },
        ),
    ]
