# Generated by Django 3.2.16 on 2023-11-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='extra',
            field=models.CharField(blank=True, default=None, help_text='Información extra para el cerificado', max_length=512, null=True, verbose_name='Información extra'),
        ),
    ]
