# Generated by Django 3.2.23 on 2023-11-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='email',
            field=models.EmailField(blank=True, default=None, help_text='E-Mail', max_length=256, null=True),
        ),
    ]
