# Generated by Django 3.2.23 on 2023-11-07 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_attendee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='email',
            field=models.EmailField(blank=True, default=None, help_text='Correo electrónico al que remitir el certificado', max_length=256, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(help_text='Evento al que asistió', on_delete=django.db.models.deletion.PROTECT, related_name='attendees', to='events.event', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='name',
            field=models.CharField(help_text='Nombre propio', max_length=256, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='surname',
            field=models.CharField(help_text='Apellidos', max_length=384, verbose_name='Apellidos'),
        ),
    ]
