# Generated by Django 3.2.23 on 2023-11-07 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_auto_20231107_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Id. público del certificado'),
        ),
    ]
