# Generated by Django 3.2.23 on 2023-11-07 10:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_attendee_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Id. público del certificado'),
        ),
    ]
