# Generated by Django 3.2.23 on 2023-11-07 11:05

import apps.certificates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_alter_attendee_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='pdf',
            field=models.FileField(
                blank=True,
                default=None,
                help_text='Generated PDF',
                max_length=512,
                null=True,
                upload_to=apps.certificates.models._issued_certificates_upload_to,
                ),
        ),
    ]
