# Generated by Django 3.2.23 on 2023-11-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_attendee_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='issued_at',
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                editable=False,
                verbose_name='Fecha de expedición',
                ),
        ),
    ]
