# Generated by Django 2.2.7 on 2020-05-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='salary',
            field=models.CharField(blank=True, max_length=80, verbose_name='Salario o rango salarial'),
        ),
    ]
