# Generated by Django 3.2.25 on 2025-02-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20220510_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ally',
            options={'ordering': ['name'], 'verbose_name': 'Aliado', 'verbose_name_plural': 'Aliados'},
        ),
    ]
