# Generated by Django 2.1 on 2018-08-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.FileField(upload_to='organizations/organization/'),
        ),
        migrations.AlterField(
            model_name='organizationrole',
            name='logo',
            field=models.FileField(blank=True, upload_to='organizations/organization_role/'),
        ),
    ]
