# Generated by Django 2.1 on 2018-08-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationcategory',
            options={'verbose_name_plural': 'organization categories'},
        ),
        migrations.AlterModelOptions(
            name='organizationsubcategory',
            options={'verbose_name_plural': 'organization subcategories'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.FileField(upload_to='organizations/sponsor/'),
        ),
        migrations.AlterField(
            model_name='organizationsubcategory',
            name='logo',
            field=models.FileField(blank=True, upload_to='organizations/group/'),
        ),
    ]
