# Generated by Django 2.1 on 2018-08-24 19:21

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('organizations', '0002_auto_20180824_1919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationSubcategory',
            new_name='OrganizationRole',
        ),
        migrations.AlterModelOptions(
            name='organizationrole',
            options={},
        ),
        migrations.RenameField(
            model_name='organizationcategory',
            old_name='subcategory',
            new_name='role',
        ),
    ]
