# Generated by Django 2.1 on 2018-08-24 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20180824_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcategory',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='organization_categories', to='organizations.OrganizationRole'),
            preserve_default=False,
        ),
    ]
