# Generated by Django 2.1 on 2018-08-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20180824_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='management_email',
        ),
        migrations.AddField(
            model_name='membership',
            name='mgmt_email',
            field=models.EmailField(blank=True, help_text='Management email of the organization used during the event', max_length=254),
        ),
    ]
