# Generated by Django 2.1 on 2018-08-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20180825_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='mgmt_email',
            new_name='management_email',
        ),
    ]
