# Generated by Django 2.2.3 on 2019-10-14 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_closed_schedule'),
        ('invoices', '0005_invoice_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='events.Event'),
        ),
    ]
