# Generated by Django 2.2.10 on 2021-05-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_remove_invoice_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='po_box',
            new_name='postal_code',
        ),
    ]
