# Generated by Django 2.1 on 2018-08-21 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('logo', models.ImageField(blank=True, upload_to='events/sponsors/sponsor/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorshipLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsorship_levels', to='events.Event')),
            ],
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsorship_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsors', to='sponsors.SponsorshipLevel'),
        ),
    ]
