# Generated by Django 2.1 on 2018-08-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='photo',
            field=models.ImageField(blank=True, upload_to='locations/location/'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='photo',
            field=models.ImageField(blank=True, upload_to='locations/venue/'),
        ),
    ]
