# Generated by Django 2.2.10 on 2021-05-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20210524_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(blank=True, help_text='Leave empty for an online event', max_length=256),
        ),
    ]
