# Generated by Django 2.1 on 2018-08-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='speaker',
        ),
        migrations.AddField(
            model_name='schedule',
            name='speaker',
            field=models.ManyToManyField(blank=True, related_name='schedule', to='speakers.Speaker'),
        ),
    ]
