# Generated by Django 2.2.4 on 2019-10-09 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20180830_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slottag',
            options={'ordering': ['name']},
        ),
    ]
