# Generated by Django 2.1 on 2018-08-25 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20180825_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='schedule.SlotLevel'),
        ),
    ]
