# Generated by Django 2.1.2 on 2018-10-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_send_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='release_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
