# Generated by Django 2.1.2 on 2018-10-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20181014_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.PositiveIntegerField(blank=True, help_text='Consecutive number within event', null=True),
        ),
    ]
