# Generated by Django 2.1.3 on 2018-11-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20181028_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.PositiveIntegerField(blank=True, help_text='Consecutive number within event (if blank it will be automatically fulfilled)', null=True),
        ),
    ]
