# Generated by Django 2.1.4 on 2019-04-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20181105_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_method',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Stripe (default)'), (2, 'Bank transference'), (3, 'PayPal')], default=1, null=True),
        ),
    ]
