# Generated by Django 2.2 on 2019-07-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_refunded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='payment_method',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Stripe (default)'), (2, 'Bank transference'), (3, 'PayPal'), (4, 'SumUp')], default=1, null=True),
        ),
    ]
