# Generated by Django 2.2.4 on 2019-08-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20190804_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='can_be_awarded',
        ),
        migrations.AddField(
            model_name='article',
            name='participate_in_raffle',
            field=models.BooleanField(default=True, help_text='Indicates if people with this article can be awarded in a potential raffle at event'),
        ),
    ]
