# Generated by Django 2.2.4 on 2019-08-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20190804_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ['name', 'description']},
        ),
        migrations.AddField(
            model_name='gift',
            name='missing_tickets',
            field=models.ManyToManyField(related_name='missing_gifts', to='tickets.Ticket'),
        ),
    ]
