# Generated by Django 2.2.4 on 2019-08-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_auto_20190806_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
