# Generated by Django 6.1.1 on 2026-09-25 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0015_auto_20220510_2236"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gift",
            options={
                "ordering": ["name", "description"],
                "verbose_name": "Obsequio",
                "verbose_name_plural": "Obsequios",
            },
        ),
        migrations.AlterModelOptions(
            name="raffle",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Sorteo",
                "verbose_name_plural": "Sorteos",
            },
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ["number"],
                "verbose_name": "Entrada",
                "verbose_name_plural": "Entradas",
            },
        ),
        migrations.AlterModelOptions(
            name="ticketcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Categoría de entrada",
                "verbose_name_plural": "Categorías de entradas",
            },
        ),
    ]
