# Generated by Django 2.1 on 2018-08-18 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0005_ticket_sold_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('icon', models.CharField(max_length=220)),
                ('href', models.CharField(help_text="url template, for example: 'mailto:{}' or 'http://t.me/{}'", max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150)),
                ('name', models.CharField(max_length=220)),
                ('email', models.EmailField(blank=True, max_length=220, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150)),
                ('title', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('time', models.TimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Event')),
                ('tags', models.ManyToManyField(related_name='talks', to='talks.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='speaker',
            name='talk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talks.Talk'),
        ),
        migrations.AddField(
            model_name='contact',
            name='social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talks.Social'),
        ),
        migrations.AddField(
            model_name='contact',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talks.Speaker'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='talk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='talks.Talk'),
        ),
    ]
