# Generated by Django 2.1 on 2018-08-25 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('speakers', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('language', models.CharField(choices=[('ES', 'Español'), ('EN', 'Inglés')], default='ES', max_length=2)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='events.Event')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='locations.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('repo', models.URLField(blank=True)),
                ('slides', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlotCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'slot categories',
            },
        ),
        migrations.CreateModel(
            name='SlotLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('order', models.PositiveIntegerField(choices=[(10, 'High'), (50, 'Medium (default)'), (100, 'Low')], default=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlotTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('order', models.PositiveIntegerField(choices=[(10, 'High'), (50, 'Medium (default)'), (100, 'Low')], default=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='slot',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='schedule.SlotCategory'),
        ),
        migrations.AddField(
            model_name='slot',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='schedule.SlotLevel'),
        ),
        migrations.AddField(
            model_name='slot',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='slots', to='schedule.SlotTag'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='schedule.Slot'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='speakers.Speaker'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='schedule.Track'),
        ),
    ]
