# Generated by Django 2.1 on 2018-08-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20180830_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='speaker',
            new_name='speakers',
        ),
    ]
