# Generated by Django 3.2.13 on 2022-06-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['name']},
        ),
    ]
