# Generated by Django 3.2.13 on 2022-06-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20220602_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='color',
            field=models.CharField(default='FF0000', max_length=8),
        ),
    ]
