# Generated by Django 3.2.13 on 2022-06-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_label_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(default='EEBDDE', max_length=8),
        ),
    ]
