# Generated by Django 3.2.13 on 2022-06-23 08:11

from django.db import migrations, models

import apps.learn.colors


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_alter_label_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(default=apps.learn.colors.get_random_hex_color, max_length=8),
        ),
    ]
