# Generated by Django 3.2.13 on 2022-05-18 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20220510_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name', 'surname'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
    ]
