# Generated by Django 2.1 on 2018-08-18 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0005_ticket_sold_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150)),
                ('title', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sponsors.Sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150)),
                ('title', models.CharField(max_length=220)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Event')),
            ],
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sponsors.Type'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='types',
            field=models.ManyToManyField(through='sponsors.Sponsorship', to='sponsors.Type'),
        ),
    ]
