# Generated by Django 2.0.7 on 2018-07-09 22:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=150)),
                ('title', models.CharField(max_length=220)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('keycode', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=48)),
                ('surname', models.CharField(max_length=72)),
                ('email', models.CharField(max_length=260)),
                ('phone', models.CharField(blank=True, max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('stock', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Event')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.TicketType'),
        ),
    ]
