# Generated by Django 2.0.7 on 2018-07-14 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_types', to='events.Event'),
        ),
    ]
