# Generated by Django 2.1 on 2018-08-21 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('how_to_reach', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='events/locations/location/')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('address', models.CharField(max_length=220)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='events/locations/venue/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='events.Event')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='locations.Venue'),
        ),
    ]
