# Generated by Django 2.1 on 2018-08-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'verbose_name_plural': 'ticket categories'},
        ),
    ]
