# Generated by Django 2.1.1 on 2018-10-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='send_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
