# Generated by Django 2.1.2 on 2018-10-22 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20181014_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_image', models.ImageField(upload_to='events/badges/')),
                ('name_coordinates', models.CharField(max_length=255, verbose_name='Coordinates for Name eg: 100,50')),
                ('number_coordinates', models.CharField(max_length=255, verbose_name='Coordinates for Ticket Number eg: 100,50')),
                ('category_coordinates', models.CharField(max_length=255, verbose_name='Coordinates for Ticket Category eg: 100,50')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Article')),
            ],
        ),
    ]
