# Generated by Django 2.1.2 on 2018-11-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20181105_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='invalid',
            field=models.BooleanField(default=False),
        ),
    ]
