# Generated by Django 2.2 on 2019-04-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='member',
            name='public_membership',
            field=models.BooleanField(default=False, help_text='Si está activo, tu perfil de usuario se mostrará públicamente en la web'),
        ),
        migrations.AddField(
            model_name='member',
            name='state_id_code',
            field=models.CharField(blank=True, default=None, help_text='NIF para españoles o NIE si procede', max_length=22),
        ),
        migrations.AddField(
            model_name='member',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default=None, max_length=64),
        ),
    ]
