# Generated by Django 2.2 on 2019-04-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20190424_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='info@pythoncanarias.es', max_length=300, unique=True),
        ),
    ]
