# Generated by Django 2.2.7 on 2019-12-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='payment_date',
            new_name='received_at',
        ),
        migrations.AlterField(
            model_name='fee',
            name='valid_from',
            field=models.DateField(),
        ),
    ]
