# Generated by Django 2.2.7 on 2019-12-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_auto_20191201_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='member_category',
        ),
        migrations.AddField(
            model_name='member',
            name='is_founder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='is_honorary',
            field=models.BooleanField(default=False),
        ),
    ]
