# Generated by Django 2.2.7 on 2019-12-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20191202_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='fee_amount',
            field=models.IntegerField(choices=[(20, 'General'), (10, 'Estudiante y/o Desempleado')], default=20),
        ),
    ]
