# Generated by Django 2.2.7 on 2019-12-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_auto_20191202_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='fee_received_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
