# Generated by Django 2.2.4 on 2019-11-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name', 'surname']},
        ),
    ]
