# Generated by Django 2.1 on 2018-08-29 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20180827_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='joint_organization',
            field=models.ForeignKey(blank=True, help_text='Organizations joint with other organizations', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='joint_memberships', to='organizations.Organization'),
        ),
    ]
