# Generated by Django 2.1.4 on 2019-02-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20190118_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='bank',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
