# Generated by Django 2.1.4 on 2019-04-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20190209_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='paypal_username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
