# Generated by Django 2.1.4 on 2019-04-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organization_paypal_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
