# Generated by Django 2.2.3 on 2019-10-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_auto_20191013_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='amount',
            new_name='_amount',
        ),
    ]
