name: CI
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Execute remote deploy commands
        uses: appleboy/ssh-action@master
        with:
          host: pythoncanarias.es
          username: ${{ secrets.PRODUCTION_SSH_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          script: source ~/.pyenv/versions/pycanweb/bin/activate && cd ~/web && ./deploy.sh
